version: "3.7"

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:3000

    my-databases:
        build:
            context: .
            dockerfile: Dockerfile.mongo
        ports:
            - 27017:27017
