version: "3.7"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:3000
        volumes:
            - ./src/:/backend/src/
            - ./models/:/backend/models/
            - ./swagger/:/backend/swagger/
            - ./.env:/backend/.env

    database:
        image: mongo:5
        ports:
            - 27017:27017
