version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./src/:/PDB/src/
      - ./test/:/PDB/test/
      - ./.env:/PDB/.env

  database:
    image: mysql:8
    ports:
      - 4306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
