paths:
  /users:
    get:
      summary: 사용자 목록 가져오기
      tags: ["사용자 관리"]
      responses:
        200:
          description: 성공
          content:
            application/json:
              type: array
              schema:
                items:
                  properties:
                    og:
                      type: object
                      example:
                        {
                          "title": "네이버",
                          "description": "네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요",
                          "image": "https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png",
                        }
                    _id:
                      type: ObjectId
                      example: 63da122bbae0ac2dda1487cd
                    name:
                      type: string
                      example: 홍길동
                    email:
                      type: string
                      example: honggildong@naver.com
                    personal:
                      type: string
                      example: 123456-*******
                    prefer:
                      type: string
                      example: https://www.naver.com
                    pwd:
                      type: string
                      example: honggildong1!
                    phone:
                      type: string
                      example: "01015771577"
                    __v:
                      type: integer
                      example: 0
        422:
          description: 오류<br>사용자 DB 접속 오류
          content:
            text/plain:
              type: string
              example: NotConnectedDB
    post:
      summary: 사용자 신규 가입
      tags: ["사용자 관리", "회원가입"]
      description: "[/token/phone]의 post와 patch를 사용하여 인증이 된 전화번호를 이용해서만 신규 가입이 가능합니다."
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                newUser:
                  type: object
                  properties:
                    name:
                      type: string
                    email:
                      type: string
                    personal:
                      type: string
                    prefer:
                      type: string
                    pwd:
                      type: string
                    phone:
                      type: string
                  example:
                    {
                      name: 홍길동,
                      email: honggildong@naver.com,
                      personal: 123456-2345678,
                      prefer: https://naver.com,
                      pwd: honggildong1!,
                      phone: "01015771577",
                  }
      responses:
        200:
          description: 성공
          content:
            text/plain:
              type: ObjectId
              example: 63da122bbae0ac2dda1487cd
        422:
          description: 오류<br>인증이 완료되지 않은 휴대폰 번호로 시도한 회원가입
          content:
            text/plain:
              type: string
              example: NotAuthPhone
        423:
          description: 오류<br>이메일 형식이 맞지 않는 형태로 시도한 회원가입
          content:
            text/plain:
              type: string
              example: NotValidationEmail