version: "3.7"

services:
    my-backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 4000:3000
        volumes:
            - ./index.js:/backend/index.js
            - ./phone.js:/backend/phone.js

    my-database:
        image: mongo:5
        ports:
            - 27017:27017
